### ISSUE TITLE
BLR grammar support

### ISSUE THREAD

**Issue by rscarson** [codelion/gramtest#1]
I'd like to use this to generate tests for a relatively small BLR grammar I've written for a tool I'm building, 

However there does not appear an option to treat a grammar as such

**Comment by codelion** [comment]
@rscarson can you tell me a bit more about it? In particular I have no idea what a BLR grammar means?

**Comment by rscarson** [comment]
Sorry... that was a typo! I meant [GLR](https://en.wikipedia.org/wiki/GLR_parser)

As in an ambiguous grammar
