### ISSUE TITLE
Support EBNF grammars

### ISSUE THREAD

**Issue by marcospassos** [codelion/gramtest#12]
Any chances of adding support to EBNF?

**Comment by codelion** [comment]
It should be possible to do so, you will need to write a new [`GeneratorVistor`](https://github.com/codelion/gramtest/blob/master/src/main/java/com/sourceclear/gramtest/GeneratorVisitor.java) based on the EBNF parser. There is no EBNF grammar in the Antlr grammar repos though https://github.com/antlr/grammars-v4
