### ISSUE TITLE
outputs \r\n instead of new line characters

### ISSUE THREAD

**Issue by devilboydante** [codelion/gramtest#14]
I ran  gramtest against the provided csv.bnf. I see the output contains "\r\n" instead of new line characters as shown below
Test case 1:
"\n\n",",,"uu,"O"\r\n"c",Y
Test case 2:
"\n\n",",,""\nI","\rf"\r\nMM,"O"\r\n

**Comment by codelion** [comment]
I think that's just generated because the grammar has a carriage return + line feed

`<crlf>      ::= <cr> <lf>`
