### ISSUE TITLE
TestRunner constructors are not visible

### ISSUE THREAD

**Issue by naude-r** [codelion/gramtest#17]
hi,

have attempted to add TestRunner to my unit tests. this is failing due to the package visible constructors.

would it be possible to make the constructors public?
```
TestRunner(java.io.InputStream,java.util.concurrent.BlockingQueue<java.lang.String>,int,int,int) is not public in com.sourceclear.gramtest.TestRunner; cannot be accessed from outside package
```

the same applies to GeneratorVisitor.

**Comment by codelion** [comment]
Fixed in https://github.com/codelion/gramtest/commit/b85f1ddae051f510c5602c84ffc353f7779af0a7

**Comment by naude-r** [comment]
thank you for the quick response.
