### ISSUE TITLE
Include build instructions in your Readme.

### ISSUE THREAD

**Issue by ustegrew** [codelion/gramtest#18]
Hi! This tool looks very promising for a project of mine. Thanks for your efforts and for sharing it!

With reference to your build instructions

> We use maven as our build tool. When you compile the project 
> using maven it will generate a single Jar

Could you add a little snippet in your Readme detailing how exactly to compile your work? In particular it would need

- a list of dependencies (which software to install so it compiles)
- the exact commands used to compile it.

I did try to build it, but it failed miserably (No worries, I don't expect you to diagnose why this particular build failed - I'm just suggesting you provide the info above in your Readme).

Thanks

```
~/Downloads/dev/lib/gramtest$ sudo apt-get install maven

~/Downloads/dev/lib/gramtest$ mvn clean compile
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by com.google.inject.internal.cglib.core.$ReflectUtils$1 (file:/usr/share/maven/lib/guice.jar) to method java.lang.ClassLoader.defineClass(java.lang.String,byte[],int,int,java.security.ProtectionDomain)
WARNING: Please consider reporting this to the maintainers of com.google.inject.internal.cglib.core.$ReflectUtils$1
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
[INFO] Scanning for projects...
[INFO] 
[INFO] ------------------------------------------------------------------------
[INFO] Building gramtest 0.2.3
[INFO] ------------------------------------------------------------------------
Downloading from central: https://repo.maven.apache.org/maven2/org/antlr/antlr4-maven-plugin/4.6/antlr4-maven-plugin-4.6.pom
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 0.369 s
[INFO] Finished at: 2018-05-19T17:40:32+02:00
[INFO] Final Memory: 8M/30M
[INFO] ------------------------------------------------------------------------
[ERROR] Plugin org.antlr:antlr4-maven-plugin:4.6 or one of its dependencies could not be resolved: Failed to read artifact descriptor for org.antlr:antlr4-maven-plugin:jar:4.6: Could not transfer artifact org.antlr:antlr4-maven-plugin:pom:4.6 from/to central (https://repo.maven.apache.org/maven2): java.lang.RuntimeException: Unexpected error: java.security.InvalidAlgorithmParameterException: the trustAnchors parameter must be non-empty -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/PluginResolutionException
```

**Comment by ustegrew** [comment]
fyi, got my build to work by following https://askubuntu.com/a/991636. The problem was an unusable Java SSL keystore. On my system (kubuntu 18.04) it's a file `/etc/ssl/certs/java/cacerts`.

- I downloaded the .tar.gz version of java 8 from http://www.oracle.com/technetwork/java/javase/downloads/jdk8-downloads-2133151.html.
- Extracted the file.
- backed up my old Java keystore: `sudo mv /etc/ssl/certs/java/cacerts /etc/ssl/certs/java/cacerts.bak`
- copied the `cacerts` file from the Java I downloaded into my `/etc/ssl/certs/java` directory: `sudo cp <downloaded-jdk-root-dir>/jre/lib/security/cacerts /etc/ssl/certs/java`
- before that I had already installed maven: `sudo apt-get install maven`

With all that jazz done, I was able to build that jar file:
```
cd Downloads
git clone https://github.com/codelion/gramtest.git
cd gramtests
mvn clean package
```

When finished I found two jar files:

- bare gramtest jar, excluding dependencies: `<project-root-dir>/target/gramtest-0.2.3-jar-with-dependencies.jar`
- full jar file, with all dependencies packaged in: `<project-root-dir>/target/gramtest-0.2.3.jar`

Now trying in my IDE...

**Comment by codelion** [comment]
I think you system had other problems and thus was not able to build the project. Otherwise, it can be built using the standard maven command `mvn package` and you can run the `jar-with-dependencies` directly. I will add a note about it in the README.
