### ISSUE TITLE
Generator don't handle quote

### ISSUE THREAD

**Issue by JocaPC** [codelion/gramtest#6]
Generator do not replaces $$$ with ". JSON generator generates outputs like:

{$$$aaaaaaaa$$$:{$$$aaaaa$$$:{$$$aa$$$:{$$$$$$:,$$$$$$:},$$$aa$$$:{$$$$$$:,$$$$$$:}}

**Comment by codelion** [comment]
Thanks for the report, the $$$ were a temporary hack I had while I fixed the handling of quotes properly. This is now fixed in [latest release.](https://github.com/codelion/gramtest/releases/latest)
