### ISSUE TITLE
JSON grammar generates invalid outputs

### ISSUE THREAD

**Issue by jovanpop-msft** [codelion/gramtest#9]
I'm getting invalid JSON outputs while generating outputs with JSON grammar. Example call is:

` java -jar gramtest-0.2.1.jar -file json.bnf -tests MYTEST -max 100 -min 10 `

Outputs look like:

` {"Z":{"Z":[9,{"":,"":}],"Z":[9,{"":,"":}]},"Z":{"Z":[{"":,"":},{"":,"":}],"Z":[9,{"":,"":}]}} `

Note that there are some empty values like `"":`  for the grammar rule `<property>  ::= <string> ":" <value>`. However, `<value>` is not empty in the grammar. It seems that in some cases it generates empty symbols.

This might be a wild guess but maybe it generates empty string when it reaches the maximal depth of grammar rule. If so, it should abort test output instead of generating invalid output.

I'm using modified JSON grammar reported in #7.

**Comment by codelion** [comment]
This is fixed in master now. The solution is not ideal but it should not generate any invalid inputs now.
